### list all categories
GET {{host}}/api/v1/categories
Accept: application/json

### create a new category
# constraints: 2-50 chars, alphanumeric/spaces/hyphens only
POST {{host}}/api/v1/categories HTTP/1.1
Content-Type: application/json

{ "name" : "Architecture" }

### delete a category by ID
@categoryId = <category-id>
DELETE {{host}}/api/v1/categories/{{categoryId}}
