### get all tags
GET {{host}}/api/v1/tags
Accept: application/json

### create new tags
# constraints: 1-10 names, each 2-30 chars, alphanumeric/spaces/hyphens only
POST {{host}}/api/v1/tags
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "names": [
    "Spring Boot",
    "Redis",
    "Cache"
  ]
}

### delete a tag by ID
@tagId = 0daf0887-2c88-48dc-8e09-9b9289e04b69
DELETE {{host}}/api/v1/tags/{{tagId}}
Authorization: Bearer {{token}}
